#!/bin/sh
if [ ! -f /etc/aria2/aria2.conf ]; then
  cp /etc/aria2_default/aria2.conf /etc/aria2/aria2.conf
fi
if [ ! -f /etc/aria2/Complete ]; then
  cp -a /etc/aria2_default/Complete /etc/aria2/Complete
fi
if [ $SECRET ]; then
  grep -q "rpc-secret" /etc/aria2/aria2.conf
  if [ $? -eq 0 ];then
    sed -i '/rpc-secret/d' /etc/aria2/aria2.conf
  fi
  echo "rpc-secret=${SECRET}" >> /etc/aria2/aria2.conf    
fi
if [ $TIMEZONE ]; then
  rm -rf /etc/localtime
  echo "${TIMEZONE}" > /etc/TZ
  cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
fi
touch /etc/aria2/aria2.session
darkhttpd usr/share/ariang --port 9092
aria2c --conf-path=/etc/aria2/aria2.conf
